abbr gcm "git checkout master"
abbr gcb "git checkout -b"
abbr gco "git checkout"
abbr gbback "git checkout -"
abbr g "git"
abbr ga "git add"
abbr gc "git commit"
abbr gs "git status"
abbr gd "git diff"
abbr gl "git lg"
abbr gpu "git push"
abbr gpl "git pull"
