"$schema" = "https://starship.rs/config-schema.json"

format = """$directory$git_branch$git_commit$git_state$git_status$cmd_duration
$jobs$battery$time$container$sudo$character"""
continuation_prompt = "[∙](bright-black) "
scan_timeout = 30
command_timeout = 500
add_newline = true

[directory]
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
style = "cyan bold"
read_only = "🔒"
read_only_style = "red"

[git_branch]
format = "on [$symbol$branch(:$remote_branch)]($style) "
symbol = " "
style = "bold purple"

[git_commit]
commit_hash_length = 7
format = '[\($hash$tag\)]($style) '
style = "green bold"
only_detached = true
tag_symbol = " 🏷  "

[git_state]
style = "bold yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "red bold"
stashed = '\$'
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
conflicted = "="
deleted = "✘"
renamed = "»"
modified = "!"
staged = "+"
untracked = "?"

[cmd_duration]
min_time = 2000
format = "took [$duration]($style) "
style = "yellow bold"

[jobs]
threshold = 1
symbol_threshold = 1
number_threshold = 2
format = "[$symbol$number]($style) "
symbol = "✦"
style = "bold blue"

[battery]
format = "[$symbol$percentage]($style) "
full_symbol = "● "
charging_symbol = "⚡ "
discharging_symbol = "◉ "

[[battery.display]]
threshold = 10
style = "red bold"

[time]
format = "at [$time]($style) "
style = "bold yellow"
use_12hr = false
disabled = false

[container]
format = '[$symbol \[$name\]]($style) '
symbol = "⬢"
style = "red bold dimmed"

[sudo]
format = "[as $symbol]($style)"
symbol = "🧙 "
style = "bold blue"
disabled = false

[character]
format = "$symbol "
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
vimcmd_visual_symbol = "[❮](bold yellow)"
vimcmd_replace_symbol = "[❮](bold purple)"
vimcmd_replace_one_symbol = "[❮](bold purple)"
