[misc]
assume_yes = true
cleanup = true
disable = ["vim", "gcloud", "containers", "vscode", "pnpm", "yarn", "ruby_gems", "node", "gem", "skills"]

[pre_commands]
"Neovim plugins sync" = "nvim --headless '+Lazy sync' +qa"

[commands]
"Mise tools update" = "mise upgrade"
"UV tools update" = "uv tool upgrade --all"

[brew]
greedy_cask = true
